services:
  springboot:
    image: gpemvjtmxm/test-app:latest
    container_name: test-app
    restart: always
    env_file:
      - ./src/main/resources/.env
    environment:
      - TZ=Asia/Seoul
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yml
      - ./docker/tempo/tempo-data
    ports:
      - "3110:3100"  # Tempo
      - "9411:9411" # zipkin

  loki:
    image: grafana/loki:latest
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:latest
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./docker/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
