info:
  app:
    name: TEST
    company: DevPumpkin
spring:
  application:
    name: test
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]
server:
  shutdown: graceful
  servlet:
    session:
      timeout: 0
logging:
  pattern:
    correlation: ["${spring.application.name:}", "%X{traceId:-}", "%X{spanId:-}"]

management:
  server:
    port: 8080
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  observations:
    key-values:
      application: test-service
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health, info, loggers, metrics, prometheus"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests=true:
  tracing:
    sampling:
      probability: 1.0
---
spring:
  config:
    activate:
      on-profile: local
