spring:
  application:
    name: test
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]
server:
  shutdown: graceful
  servlet:
    session:
      timeout: 0

info:
  app:
    name: TEST
    company: DevPumpkin

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  observations:
    key-values:
      application: test-service
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health, info, loggers, metrics, prometheus"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests=true:
  tracing:
    propagation:
      type: w3c
    enabled: true
    sampling:
      probability: 1.0
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
---
spring:
  config:
    activate:
      on-profile: local
