global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'test-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['test-app:8080']
